# Questo è un file di configurazione YAML per Home Assistant
# per l'integrazione di un sistema Eurotherm tramite Modbus TCP.
# Configurazione per "Clima Genitori" (ZONE ID 0) e Temperatura Esterna.
#
# Basato sul manuale SmartComfort 365 Rev.06.
# STRUTTURA CORRETTA SECONDO LA DOCUMENTAZIONE UFFICIALE DI HOME ASSISTANT MODBUS

modbus:
  - name: "eurotherm_controller" # Nome dell'hub a cui le entità faranno riferimento
    type: tcp
    host: 192.168.178.85
    port: 502
    #type: tcp
    #host: 192.168.178.85
    #port: 502
    #timeout: 10
    #delay: 1 # Ritardo in secondi tra le transazioni Modbus. Inizia con 1, puoi provare a ridurlo (es. 0.2, 0.5) se stabile.
    #retries: 5 # Numero di tentativi in caso di errore di comunicazione
    # close_comm_on_error: true # Opzionale: chiudi e riapri la connessione su errore
    # retry_on_empty: true # Opzionale: riprova se la risposta è vuota

sensor:
  - platform: modbus
    hub: eurotherm_controller # Riferimento all'hub definito sopra
    # --- SYSTEM INFORMATION ---
    name: "Eurotherm Temperatura Esterna"
    unique_id: "eurotherm_temperatura_esterna"
    slave: 1 # ID dello slave Modbus (solitamente 1 per TCP se il dispositivo non usa ID slave multipli)
    address: 58 # External temperature used
    input_type: holding # Tipo di registro Modbus
    data_type: int16 # Gestisce temperature positive e negative
    scale: 0.1 # Fattore di scala per ottenere il valore corretto (valore_letto * 0.1)
    offset: 0 # Offset da applicare dopo la scala (non necessario qui)
    precision: 1 # Numero di cifre decimali da visualizzare
    unit_of_measurement: "°C"
    device_class: temperature
    scan_interval: 300 # Frequenza di aggiornamento in secondi (ogni 5 minuti)

  - platform: modbus
    hub: eurotherm_controller
    # --- ZONA 1: "Clima Genitori" (ZONE ID 0) ---
    name: "Clima Genitori Modalita Operativa Eurotherm"
    unique_id: "eurotherm_clima_genitori_modalita_operativa_sensore"
    slave: 1
    address: 101 # ZONE ID (0) - Operative mode (0=Cooling, 1=Heating)
    input_type: holding
    data_type: uint16
    scan_interval: 60

  - platform: modbus
    hub: eurotherm_controller
    name: "Clima Genitori Modalita Zona Eurotherm"
    unique_id: "eurotherm_clima_genitori_modalita_zona_sensore"
    slave: 1
    address: 102 # ZONE ID (0) - Zone mode (0=Home, 1=Off, 2=Away, 3=Holiday(RO))
    input_type: holding
    data_type: uint16
    scan_interval: 60

  # --- "Base Eurotherm Genitori" (Assunta come MODULE 1 / BASE ID 0) ---
  # Room ID 0: "[Genitori] Stanza Badante"
  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Stanza Badante Temperatura Ambiente"
    unique_id: "eurotherm_genitori_stanza_badante_temp_ambiente"
    slave: 1
    address: 1205 # MODULE 1, Room ID 0 - Current temperature
    input_type: holding
    data_type: int16
    scale: 0.1
    precision: 1
    unit_of_measurement: "°C"
    device_class: temperature
    scan_interval: 30

  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Stanza Badante Umidita"
    unique_id: "eurotherm_genitori_stanza_badante_umidita"
    slave: 1
    address: 1206 # MODULE 1, Room ID 0 - Current humidity
    input_type: holding
    data_type: uint16
    scale: 1 # Assumendo che il valore 0-100 sia letto direttamente. Se fosse 0-1000 per 0.0-100.0%, scale: 0.1, precision: 1
    precision: 0
    unit_of_measurement: "%"
    device_class: humidity
    scan_interval: 60

  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Stanza Badante Temperatura Target Sensore"
    unique_id: "eurotherm_genitori_stanza_badante_temp_target_sensore"
    slave: 1
    address: 1208 # MODULE 1, Room ID 0 - Current target temperature (RO)
    input_type: holding
    data_type: int16
    scale: 0.1
    precision: 1
    unit_of_measurement: "°C"
    device_class: temperature
    scan_interval: 60

  # Room ID 1: "[Genitori] Bagno Grande"
  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Bagno Grande Temperatura Ambiente"
    unique_id: "eurotherm_genitori_bagno_grande_temp_ambiente"
    slave: 1
    address: 1605
    input_type: holding
    data_type: int16
    scale: 0.1
    precision: 1
    unit_of_measurement: "°C"
    device_class: temperature
    scan_interval: 30

  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Bagno Grande Temperatura Target Sensore"
    unique_id: "eurotherm_genitori_bagno_grande_temp_target_sensore"
    slave: 1
    address: 1608
    input_type: holding
    data_type: int16
    scale: 0.1
    precision: 1
    unit_of_measurement: "°C"
    device_class: temperature
    scan_interval: 60

  # Room ID 2: "[Genitori] Camera Matrimoniale"
  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Camera Matrimoniale Temperatura Ambiente"
    unique_id: "eurotherm_genitori_camera_matrimoniale_temp_ambiente"
    slave: 1
    address: 2005
    input_type: holding
    data_type: int16
    scale: 0.1
    precision: 1
    unit_of_measurement: "°C"
    device_class: temperature
    scan_interval: 30

  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Camera Matrimoniale Umidita"
    unique_id: "eurotherm_genitori_camera_matrimoniale_umidita"
    slave: 1
    address: 2006
    input_type: holding
    data_type: uint16
    scale: 1
    precision: 0
    unit_of_measurement: "%"
    device_class: humidity
    scan_interval: 60

  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Camera Matrimoniale Temperatura Target Sensore"
    unique_id: "eurotherm_genitori_camera_matrimoniale_temp_target_sensore"
    slave: 1
    address: 2008
    input_type: holding
    data_type: int16
    scale: 0.1
    precision: 1
    unit_of_measurement: "°C"
    device_class: temperature
    scan_interval: 60

  # Room ID 3: "[Genitori] Soggiorno"
  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Soggiorno Temperatura Ambiente"
    unique_id: "eurotherm_genitori_soggiorno_temp_ambiente"
    slave: 1
    address: 2405
    input_type: holding
    data_type: int16
    scale: 0.1
    precision: 1
    unit_of_measurement: "°C"
    device_class: temperature
    scan_interval: 30

  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Soggiorno Umidita"
    unique_id: "eurotherm_genitori_soggiorno_umidita"
    slave: 1
    address: 2406
    input_type: holding
    data_type: uint16
    scale: 1
    precision: 0
    unit_of_measurement: "%"
    device_class: humidity
    scan_interval: 60

  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Soggiorno Temperatura Target Sensore"
    unique_id: "eurotherm_genitori_soggiorno_temp_target_sensore"
    slave: 1
    address: 2408
    input_type: holding
    data_type: int16
    scale: 0.1
    precision: 1
    unit_of_measurement: "°C"
    device_class: temperature
    scan_interval: 60

  # Room ID 4: "[Genitori] Bagno Tondo"
  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Bagno Tondo Temperatura Ambiente"
    unique_id: "eurotherm_genitori_bagno_tondo_temp_ambiente"
    slave: 1
    address: 2805
    input_type: holding
    data_type: int16
    scale: 0.1
    precision: 1
    unit_of_measurement: "°C"
    device_class: temperature
    scan_interval: 30

  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Bagno Tondo Temperatura Target Sensore"
    unique_id: "eurotherm_genitori_bagno_tondo_temp_target_sensore"
    slave: 1
    address: 2808
    input_type: holding
    data_type: int16
    scale: 0.1
    precision: 1
    unit_of_measurement: "°C"
    device_class: temperature
    scan_interval: 60

  # Room ID 5: "[Genitori] Lavanderia"
  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Lavanderia Temperatura Ambiente"
    unique_id: "eurotherm_genitori_lavanderia_temp_ambiente"
    slave: 1
    address: 3205
    input_type: holding
    data_type: int16
    scale: 0.1
    precision: 1
    unit_of_measurement: "°C"
    device_class: temperature
    scan_interval: 30

  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Lavanderia Umidita"
    unique_id: "eurotherm_genitori_lavanderia_umidita"
    slave: 1
    address: 3206
    input_type: holding
    data_type: uint16
    scale: 1
    precision: 0
    unit_of_measurement: "%"
    device_class: humidity
    scan_interval: 60

  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Lavanderia Temperatura Target Sensore"
    unique_id: "eurotherm_genitori_lavanderia_temp_target_sensore"
    slave: 1
    address: 3208
    input_type: holding
    data_type: int16
    scale: 0.1
    precision: 1
    unit_of_measurement: "°C"
    device_class: temperature
    scan_interval: 60

climate:
  - platform: modbus
    hub: eurotherm_controller # Riferimento all'hub
    # --- TERMOSTATI PER ZONA 1: "Clima Genitori" ---
    # Room ID 0: "[Genitori] Stanza Badante"
    name: "[Genitori] Termostato Stanza Badante"
    unique_id: "eurotherm_genitori_termostato_stanza_badante"
    slave: 1
    current_temperature_entity_id: sensor.genitori_stanza_badante_temperatura_ambiente
    target_temperature_entity_id: sensor.genitori_stanza_badante_temperatura_target_sensore # Legge il target attuale dal sensore (RO)
    target_temp_register: 1210 # MODULE 1, Room ID 0 - Manual temperature (RW) - Per IMPOSTARE il target
    target_temp_register_type: holding # Tipo di registro per la scrittura del target
    # Registro per IMPOSTARE la modalità della stanza (Auto/Manuale/Off)
    # Nota: la modalità "Off" (valore 0) è indicata come RO (Read Only) nel manuale per il registro Mode (1209).
    # Questo significa che impostare "Off" tramite questo climate potrebbe non funzionare.
    # La modalità "Off" della zona potrebbe dover essere controllata tramite il registro 102 (Modalita Zona Eurotherm).
    hvac_mode_register:
      address: 1209 # MODULE 1, Room ID 0 - Mode (RW)
      # Valori che Home Assistant scriverà per le rispettive modalità
      values:
        off: 0       # Tenta di scrivere 0 per Off (potrebbe non funzionare se RO)
        auto: 1      # Scrive 1 per Auto
        heat: 2      # Scrive 2 per Manual (rappresentato come 'heat' in HA)
        # cool: 2 # Se il sistema supporta il raffrescamento e usi la stessa logica manuale
    # Modalità supportate dal termostato in Home Assistant
    hvac_modes:
      - "off"
      - "auto"
      - "heat" # Rappresenta la modalità Manuale del termostato Eurotherm.
               # Se il tuo sistema può anche raffrescare attivamente e vuoi controllarlo
               # potresti aggiungere "cool" e/o "heat_cool" se il registro mode lo supporta.
               # Per ora, "heat" implica che il termostato è attivo in modalità manuale.
    min_temp: 15.0 # Temperatura minima impostabile
    max_temp: 30.0 # Temperatura massima impostabile
    temp_step: 0.1 # Incremento per l'impostazione della temperatura (manuale dice 0.1°C)
    precision: 0.1 # Precisione di visualizzazione della temperatura in HA
    data_type: int16 # Tipo di dato per scrivere la temperatura target
    scale: 0.1 # Scala per scrivere la temperatura target (valore_HA * 10 = valore_da_scrivere, se data_type è int16 e scale è 0.1, HA gestisce la conversione)


  # Room ID 1: "[Genitori] Bagno Grande"
  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Termostato Bagno Grande"
    unique_id: "eurotherm_genitori_termostato_bagno_grande"
    slave: 1
    current_temperature_entity_id: sensor.genitori_bagno_grande_temperatura_ambiente
    target_temperature_entity_id: sensor.genitori_bagno_grande_temperatura_target_sensore
    target_temp_register: 1610
    target_temp_register_type: holding
    hvac_mode_register:
      address: 1609
      values: { off: 0, auto: 1, heat: 2 }
    hvac_modes: ["off", "auto", "heat"]
    min_temp: 15.0
    max_temp: 30.0
    temp_step: 0.1
    precision: 0.1
    data_type: int16
    scale: 0.1

  # Room ID 2: "[Genitori] Camera Matrimoniale"
  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Termostato Camera Matrimoniale"
    unique_id: "eurotherm_genitori_termostato_camera_matrimoniale"
    slave: 1
    current_temperature_entity_id: sensor.genitori_camera_matrimoniale_temperatura_ambiente
    target_temperature_entity_id: sensor.genitori_camera_matrimoniale_temperatura_target_sensore
    target_temp_register: 2010
    target_temp_register_type: holding
    hvac_mode_register:
      address: 2009
      values: { off: 0, auto: 1, heat: 2 }
    hvac_modes: ["off", "auto", "heat"]
    min_temp: 15.0
    max_temp: 30.0
    temp_step: 0.1
    precision: 0.1
    data_type: int16
    scale: 0.1

  # Room ID 3: "[Genitori] Soggiorno"
  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Termostato Soggiorno"
    unique_id: "eurotherm_genitori_termostato_soggiorno"
    slave: 1
    current_temperature_entity_id: sensor.genitori_soggiorno_temperatura_ambiente
    target_temperature_entity_id: sensor.genitori_soggiorno_temperatura_target_sensore
    target_temp_register: 2410
    target_temp_register_type: holding
    hvac_mode_register:
      address: 2409
      values: { off: 0, auto: 1, heat: 2 }
    hvac_modes: ["off", "auto", "heat"]
    min_temp: 15.0
    max_temp: 30.0
    temp_step: 0.1
    precision: 0.1
    data_type: int16
    scale: 0.1

  # Room ID 4: "[Genitori] Bagno Tondo"
  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Termostato Bagno Tondo"
    unique_id: "eurotherm_genitori_termostato_bagno_tondo"
    slave: 1
    current_temperature_entity_id: sensor.genitori_bagno_tondo_temperatura_ambiente
    target_temperature_entity_id: sensor.genitori_bagno_tondo_temperatura_target_sensore
    target_temp_register: 2810
    target_temp_register_type: holding
    hvac_mode_register:
      address: 2809
      values: { off: 0, auto: 1, heat: 2 }
    hvac_modes: ["off", "auto", "heat"]
    min_temp: 15.0
    max_temp: 30.0
    temp_step: 0.1
    precision: 0.1
    data_type: int16
    scale: 0.1

  # Room ID 5: "[Genitori] Lavanderia"
  - platform: modbus
    hub: eurotherm_controller
    name: "[Genitori] Termostato Lavanderia"
    unique_id: "eurotherm_genitori_termostato_lavanderia"
    slave: 1
    current_temperature_entity_id: sensor.genitori_lavanderia_temperatura_ambiente
    target_temperature_entity_id: sensor.genitori_lavanderia_temperatura_target_sensore
    target_temp_register: 3210
    target_temp_register_type: holding
    hvac_mode_register:
      address: 3209
      values: { off: 0, auto: 1, heat: 2 }
    hvac_modes: ["off", "auto", "heat"]
    min_temp: 15.0
    max_temp: 30.0
    temp_step: 0.1
    precision: 0.1
    data_type: int16
    scale: 0.1

# --- ZONA 2: "Clima Casa" (ZONE ID 1) ---
# Sezione commentata per ora, da definire in futuro.
# ...

# Note sulla configurazione:
# 1. Salva questo codice nel tuo file `packages/eurotherm_modbus.yaml` (o come l'hai chiamato).
# 2. Verifica la configurazione in HA (Strumenti per sviluppatori -> YAML) e riavvia.
# 3. Controlla i log per errori. Se necessario, aumenta il livello di log per modbus:
# logger:
#   default: info # o warning
#   logs:
#     homeassistant.components.modbus: debug
#     pymodbus: debug # Per debug a basso livello della comunicazione Modbus
